variable "location" {}
variable "resource_group_name" {}
variable "vnet_id" {}
variable "app_plan_subnet_id" {}
variable "app_gateway_subnet_id" {}
variable "services_subnet_id" {}
variable "apim_subnet_id" {}
variable "env" {}
variable "log_analytics_sku" {}
variable "app_plan_sku" {}
variable "runner_ip" {}
variable "app_zone_id" {}
variable "app_registration_id" {}
variable "app_registration_uri" {}
variable "tenant_id" {}
variable "image_tag_suffix" {}
variable "fhir_url" {}
variable "app_insights_instrumentation_key" {}
variable "current_object_id" {}
variable "vault_zone_id" {}
variable "storage_zone_id" {}
variable "azure_cli_client_id" {}
variable "sp_client_id" {}
variable "health_services_principal_id" {}
variable "acr_login_server" {
  type = string
}
variable "acr_id" {
  type = string
}