name: CI

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    bvt:
        name: Build Verification Test
        uses: ./.github/workflows/bvt.yaml
        with:
            service_name: 'api'
            project_folder: 'Api'
        secrets: inherit
    
    swagger_docs:
        runs-on: ubuntu-latest
        name: Generate Swagger Docs
        needs: bvt
        steps:
            - name: Checkout Repository
              uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

            - name: Build and Publish Swagger Docs
              run: mkdir -p ${{ github.workspace }}/swagger-artifacts && bash ${{ github.workspace }}/.pipelines/scripts/generate-swagger.sh ${{ github.workspace }}/swagger-artifacts
              env:
                  ASPNETCORE_ENVIRONMENT: 'Local'

            - name: Publish Swagger Doc as Pipeline Artifact
              uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              with:
                  name: SwaggerDoc
                  path: ${{ github.workspace }}/swagger-artifacts/dex-swagger.json
            
    static_code_analysis:
        name: Static Code Analysis
        uses: ./.github/workflows/static-code-analysis.yaml
    
    
