name: Static Code Analysis

on:
  workflow_call:

jobs:
    static-code-analysis:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

            - name: DevSkim Security Analysis
              run: |
                dotnet tool install -g Microsoft.CST.DevSkim.CLI
                devskim analyze --source-code ${{ github.workspace }}/src --output-file ${{ github.workspace }}/devskim-results.sarif -f sarif

            - name: Publish DevSkim Security Analysis Results
              uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
              if: always()
              with:
                name: CodeAnalysisLogs
                path: ${{ github.workspace }}/devskim-results.sarif

            - name: Fail If Critical or Important Severity Found
              run: |
                if grep -q -E '("DevSkimSeverity":"Critical"|"DevSkimSeverity":"Important")' ${{ github.workspace }}/devskim-results.sarif; then
                  echo "Critical or Important severity found in devskim-results.sarif. Failing the pipeline."
                  exit 1
                fi

            - name: Set up Python
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
              with:
                  python-version: '3.x'

            - name: Create pre-commit requirements file
              run: |
                echo "pre-commit == 3.7.1 --hash=sha256:fae36fd1d7ad7d6a5a1c0b0d5adb2ed1a3bda5a21bf6c3e5372073d7a11cd4c5" > requirements.txt  
                echo "cfgv == 3.4.0 --hash=sha256:b5b1d8719685a8621ac064030de39a2151ee5d37cc1a30cf2e86383bb8bb86b8" >> requirements.txt  

            - name: Install pre-commit
              run: python -m pip install -r ./requirements.txt --no-deps

            - name: Run pre-commit checks
              run: pre-commit run --all-files --show-diff-on-failure
